// Custom Worker entry. Re-uses the OpenNext-generated fetch handler (serving the
// Next.js app) and adds a scheduled() handler so Cloudflare Cron Triggers can
// drive the tracking and digest jobs — all on one Worker.

// Generated by `opennextjs-cloudflare build`; absent until then.
// @ts-ignore - resolved at bundle time
import openNextHandler from "./.open-next/worker.js";
import { trackAuthors } from "./lib/jobs/trackAuthors";
import { dispatchDigests } from "./lib/jobs/dispatchDigests";

const TRACK_CRON = "0 13 * * *";
const DISPATCH_CRON = "0 14 * * *";

export default {
  fetch: openNextHandler.fetch,

  async scheduled(event, env, ctx) {
    if (event.cron === TRACK_CRON) {
      ctx.waitUntil(trackAuthors(env));
    } else if (event.cron === DISPATCH_CRON) {
      ctx.waitUntil(dispatchDigests(env));
    } else {
      // Unknown schedule: run both to be safe.
      ctx.waitUntil(
        (async () => {
          await trackAuthors(env);
          await dispatchDigests(env);
        })(),
      );
    }
  },
} satisfies ExportedHandler<CloudflareEnv>;
